sudo: false
os:
 - linux
language: d
d:
 - ldc-1.1.0
 - ldc-1.1.1
 - ldc-1.2.0-beta1
addons:
  apt:
    packages:
      - blas
      - gcc
      - gfortran
branches:
  only:
    - master
script:
 - cd examples/ && dub gemm_example.d && cd ../
 - cd examples/ && dub hemm_example.d && cd ../
 - cd bench/ && dub gemm_report.d && cd ../
 - bash -e test.sh

matrix:
    allow_failures:
    - {d: ldc-1.2.0-beta1}


notifications:
  email:
    - ilyayaroshenko@gmail.com

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d2d7cb29fc776c5eaeef
    on_success: change
    on_failure: always
    on_start: never
