sudo: false
os:
 - linux
 - osx
language: d
d:
 - ldc-1.1.0-beta2
env:
 - ARCH=x86_64
 - BLAS=3.6.0
 - CPUID=0.4.2
branches:
  only:
    - master
script:
 - bash -e test.sh

notifications:
  email:
    - devteam@mir.rocks

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d2d7cb29fc776c5eaeef
    on_success: change
    on_failure: always
    on_start: never
