language: d
d:
  - dmd
  - dmd-2.068.2
  - dmd-2.067.1
  - dmd-2.066.1
  - gdc
  - ldc

install:
  - curl -fsSLO https://raw.githubusercontent.com/D-Programming-Language/tools/v2.068.2/rdmd.d
  - ${DMD} rdmd.d
  - mv rdmd $(dirname $(which ${DMD}))

script: ./travis.sh

sudo: false
addons:
  apt:
    packages:
    - libcairo2
    - libcairo2-dev
    - fonts-dejavu-core

env:
  - MINIMAL=0
  - MINIMAL=1
