sudo: false
os:
 - linux
 - osx
language: d
d:
 - ldc-1.2.0
 - ldc-1.3.0-beta1
addons:
  apt:
    packages:
      - libblas-dev
      - libcblas-dev
      - gcc
      - gfortran
branches:
  only:
    - master
script:
 - cd examples/ && dub --single --build=release gemm_example.d && cd ../
 - cd examples/ && dub --single --build=release hemm_example.d && cd ../
 - cd bench/ && dub --single --build=release gemm_report.d && cd ../
 - bash -e test.sh

matrix:
    allow_failures:
    - {d: ldc-1.2.0}
    - {os: osx}


notifications:
  email:
    - ilyayaroshenko@gmail.com

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d2d7cb29fc776c5eaeef
    on_success: change
    on_failure: always
    on_start: never
