sudo: false
os:
 - linux
language: d
d:
 - ldc-1.1.0-beta6
addons:
  apt:
    packages:
      - gcc
      - gfortran
branches:
  only:
    - master
script:
 - bash -e test.sh

notifications:
  email:
    - ilyayaroshenko@gmail.com

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d2d7cb29fc776c5eaeef
    on_success: change
    on_failure: always
    on_start: never
