sudo: false
os:
 - linux
 - osx
language: d
d:
 - ldc-1.1.0-beta2
env:
 - ARCH=x86_64
 - BLAS=3.6.0
 - CPUID=0.4.2
matrix:
  include:
    - {os: linux, d: ldc-1.1.0-beta2, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
branches:
  only:
    - master
script:
 - dub build --arch=$ARCH -build-mode=singleFile --force --config=static --parallel --build=target-native
 - ar -z libmir-glas.a
 - dub fetch mir-cpuid --version=$CPUID --cache=local
 - cd mir-cpuid-$CPUID/mir-cpuid
 - dub build --arch=$ARCH -build-mode=singleFile --force --parallel
 - ar -z libmir-cpuid.a
 - cd ../../
 - curl -Os http://www.netlib.org/blas/blas-"$BLAS".tgz
 - tar zxvf blas-"$BLAS".tgz
 - cd BLAS-$BLAS
 - make -j
 - ar cr libblas_mix.a isamax.o sasum.o saxpy.o scopy.o sdot.o snrm2.o srot.o srotg.o sscal.o sswap.o sdsdot.o srotmg.o srotm.o sgemv.o sgbmv.o ssymv.o ssbmv.o sspmv.o strmv.o stbmv.o stpmv.o strsv.o stbsv.o stpsv.o sger.o ssyr.o sspr.o ssyr2.o sspr2.o ssyrk.o ssyr2k.o strmm.o strsm.o  idamax.o dasum.o daxpy.o dcopy.o ddot.o dnrm2.o drot.o drotg.o dscal.o dsdot.o dswap.o drotmg.o drotm.o dgemv.o dgbmv.o dsymv.o dsbmv.o dspmv.o dtrmv.o dtbmv.o dtpmv.o dtrsv.o dtbsv.o dtpsv.o dger.o dsyr.o dspr.o dsyr2.o dspr2.o dsyrk.o dsyr2k.o dtrmm.o dtrsm.o scabs1.o scasum.o scnrm2.o icamax.o caxpy.o ccopy.o cdotc.o cdotu.o csscal.o crotg.o cscal.o cswap.o csrot.o cgemv.o cgbmv.o chemv.o chbmv.o chpmv.o ctrmv.o ctbmv.o ctpmv.o ctrsv.o ctbsv.o ctpsv.o cgerc.o cgeru.o cher.o chpr.o cher2.o chpr2.o csyrk.o csyr2k.o ctrmm.o ctrsm.o cherk.o cher2k.o dcabs1.o dzasum.o dznrm2.o izamax.o zaxpy.o zcopy.o zdotc.o zdotu.o zdscal.o zrotg.o zscal.o zswap.o zdrot.o zgemv.o zgbmv.o zhemv.o zhbmv.o zhpmv.o ztrmv.o ztbmv.o ztpmv.o ztrsv.o ztbsv.o ztpsv.o zgerc.o zgeru.o zher.o zhpr.o zher2.o zhpr2.o zsyrk.o zsyr2k.o ztrmm.o ztrsm.o zherk.o zher2k.o lsame.o xerbla_array.o ../*.o ../mir-cpuid-$CPUID/mir-cpuid/*.o
 - libblas_mix.a
 - cd ..
 - curl -Os http://www.netlib.org/blas/blast-forum/cblas.tgz
 - cd CBLAS
 - rm -rf Makefile.in
 - ln -s Makefile.LINUX Makefile.in
 - make -j
 - cd ..
after_success:
 - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - devteam@mir.rocks

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d2d7cb29fc776c5eaeef
    on_success: change
    on_failure: always
    on_start: never
