sudo: false
os:
 - linux
 - osx
language: d
d:
 - ldc-1.1.0-beta2
env:
 - ARCH="x86_64"
matrix:
  include:
    - {os: linux, d: ldc-1.1.0-beta2, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
branches:
  only:
    - master
script:
 - echo "$ARCH"
 - dub fetch mir-cpuid && dub build --arch "$ARCH" mir-cpuid
 - dub test --arch "$ARCH" --build=unittest-cov
 - dub test --arch "$ARCH" --build=unittest-release
after_success:
 - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - devteam@mir.rocks

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d2d7cb29fc776c5eaeef
    on_success: change
    on_failure: always
    on_start: never
