sudo: false
os:
 - linux
 - osx
language: d
d:
 - ldc-1.1.0-beta2
addons:
  apt:
    packages:
      - gcc
      - fortran
branches:
  only:
    - master
script:
 - bash -e test.sh

notifications:
  email:
    - devteam@mir.rocks

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d2d7cb29fc776c5eaeef
    on_success: change
    on_failure: always
    on_start: never
